name: mosaiks
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - contextily
  - rasterio
  - scipy
  - cartopy
  - xarray
  - netcdf4
  - jupyterlab-system-monitor
  - statsmodels
  - pyarrow
  - scikit-learn
  - scipy
  - seaborn 
